version: '3'
services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - /d/docker/MySQL/db/data:/var/lib/mysql
    - /d/docker/MySQL/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
    - 3306:3306